### ISSUE TITLE
Access-token

### ISSUE THREAD

**Issue by XinZheng-SH** [PetterKraabol/Twitch-Chat-Downloader#102]
C:\Users\zheng>tcd --video 794904548
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\tcd.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\tcd\__init__.py", line 65, in main
    Arguments().oauth_token = requests.post(f"https://id.twitch.tv/oauth2/token"
KeyError: 'access_token'

**Comment by XinZheng-SH** [comment]
Duplicated
