### ISSUE TITLE
Access token problem

### ISSUE THREAD

**Issue by XinZheng-SH** [PetterKraabol/Twitch-Chat-Downloader#103]
C:\Users\zheng>tcd --video 794904548
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\tcd.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\tcd\__init__.py", line 65, in main
    Arguments().oauth_token = requests.post(f"https://id.twitch.tv/oauth2/token"
KeyError: 'access_token'

**Comment by cmax110** [comment]
make sure you've got your client id and secret from here https://dev.twitch.tv/console/apps
then you need to set them in tcd by passing the arguments first
so run 
`tcd --client-id CLIENT_ID`
`tcd --client-secret CLIENT_SECRET`
then you should be able to run your tcd command

**Comment by idilkylmz** [comment]
I got my id and secret from the twitch app console but still I get this error

Traceback (most recent call last):
  File "/home/idil/.local/bin/tcd", line 8, in <module>
    sys.exit(main())
  File "/home/idil/.local/lib/python3.8/site-packages/tcd/__init__.py", line 65, in main
    Arguments().oauth_token = requests.post(f"https://id.twitch.tv/oauth2/token"
KeyError: 'access_token'
