### ISSUE TITLE
script broken due to twitch API

### ISSUE THREAD

**Issue by vilapupu** [PetterKraabol/Twitch-Chat-Downloader#111]
As of now youtube-dl and TwitchLeecher as well as this python script is broken. I'm not sure if it can be fixed, but I can't download chat logs to archive them because of this.

Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\AppData\Roaming\Python\Python39\Scripts\tcd.exe\__main__.py", line 7, in <module>
  File "C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\tcd\__init__.py", line 89, in main
    Downloader().videos(Arguments().video_ids)
  File "C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\tcd\downloader.py", line 183, in videos
    self.video(video)
  File "C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\tcd\downloader.py", line 100, in video
    for comment in video.comments:
  File "C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\twitch\v5\resources\comments.py", line 24, in __iter__
    yield v5.Comment(api=self._api, data=comment)
  File "C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\twitch\v5\models\comment.py", line 78, in __init__
    self.commenter: Commenter = Commenter(data.get('commenter'))
  File "C:\Users\USER\AppData\Roaming\Python\Python39\site-packages\twitch\v5\models\comment.py", line 13, in __init__
    self.display_name: str = data.get('display_name')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by vilapupu** [comment]
seems like it was a problem for a twitch VOD that, for some reason, did not save the chat. The stream crashed and restarted as a 2nd VOD so that's probably why. First time seeing a VOD with missing chat log though.
