### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by Skillkiller** [PetterKraabol/Twitch-Chat-Downloader#112]
Hello,
I have an error with only one specific video. The command looks like this: ``tcd --video 873597125 -f json``
This is the complete console output with error:
```
C:\Users\u15021291\Desktop\chats\neu2>tcd --video 873597125 -f json
[Eng / Ger] Maybe the final run!?
Traceback (most recent call last):
  File "c:\users\u15021291\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\u15021291\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\u15021291\AppData\Local\Programs\Python\Python37-32\Scripts\tcd.exe\__main__.py", line 7, in <module>
  File "c:\users\u15021291\appdata\local\programs\python\python37-32\lib\site-packages\tcd\__init__.py", line 89, in main
    Downloader().videos(Arguments().video_ids)
  File "c:\users\u15021291\appdata\local\programs\python\python37-32\lib\site-packages\tcd\downloader.py", line 183, in videos
    self.video(video)
  File "c:\users\u15021291\appdata\local\programs\python\python37-32\lib\site-packages\tcd\downloader.py", line 100, in video
    for comment in video.comments:
  File "c:\users\u15021291\appdata\local\programs\python\python37-32\lib\site-packages\twitch\v5\resources\comments.py", line 24, in __iter__
    yield v5.Comment(api=self._api, data=comment)
  File "c:\users\u15021291\appdata\local\programs\python\python37-32\lib\site-packages\twitch\v5\models\comment.py", line 78, in __init__
    self.commenter: Commenter = Commenter(data.get('commenter'))
  File "c:\users\u15021291\appdata\local\programs\python\python37-32\lib\site-packages\twitch\v5\models\comment.py", line 13, in __init__
    self.display_name: str = data.get('display_name')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by vanyamlb** [comment]
I confirm this error. I get it when I scan some channels after different amounts of chats downloaded. please get it fixed :)

**Comment by vanyamlb** [comment]
@PetterKraabol  did I understand correctly that the error will be fixed with the upcoming update? Thank you :)
