### ISSUE TITLE
Client Authentication Broken

### ISSUE THREAD

**Issue by Snuupy** [PetterKraabol/Twitch-Chat-Downloader#131]
```
snuupy@SnuT14:~$ tcd
Traceback (most recent call last):
  File "/home/snuupy/.local/lib/python3.8/site-packages/requests/models.py", line 384, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 392, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 2, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://id.twitch.tv/oauth2/token?client_id=xxxxxxxxxxxx&client_secret=xxxxxxxxxxxx&grant_type=client_credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/snuupy/.local/bin/tcd", line 8, in <module>
    sys.exit(main())
  File "/home/snuupy/.local/lib/python3.8/site-packages/tcd/__init__.py", line 65, in main
    Arguments().oauth_token = requests.post(f"https://id.twitch.tv/oauth2/token"
  File "/home/snuupy/.local/lib/python3.8/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/snuupy/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/snuupy/.local/lib/python3.8/site-packages/requests/sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "/home/snuupy/.local/lib/python3.8/site-packages/requests/sessions.py", line 443, in prepare_request
    p.prepare(
  File "/home/snuupy/.local/lib/python3.8/site-packages/requests/models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "/home/snuupy/.local/lib/python3.8/site-packages/requests/models.py", line 386, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: https://id.twitch.tv/oauth2/token?client_id=xxxxxxxxxxxxxxx&client_secret=xxxxxxxxxxxxxxxxxx&grant_type=client_credentials
```

**Comment by Snuupy** [comment]
I've ~~double~~ triple checked my client ID and secret are correct and I've set them multiple times and I am still running into this.

**Comment by garoto** [comment]
Possibly related to issue https://github.com/PetterKraabol/Twitch-Chat-Downloader/issues/127

**Comment by Snuupy** [comment]
Thanks, I must've missed it. Will close issue.
