### ISSUE TITLE
Invalid Character Mapping

### ISSUE THREAD

**Issue by ElectronicWizard** [PetterKraabol/Twitch-Chat-Downloader#17]
Getting this error only 7% in. I've tried assigning a client ID and changing cooldown, leading me to believe it's having an issue with a certain character in chat.

`Traceback (most recent call last):
  File "app.py", line 281, in <module>
    file.write(line)
  File "C:\Program Files\Python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 29-30: character maps to <undefined>
`

**Comment by ElectronicWizard** [comment]
Using RAW format seems to correct this, so I'm guessing it has to do with some unicode encoding it does.
