### ISSUE TITLE
[bug] "ValueError: 'raw' is not in list"

### ISSUE THREAD

**Issue by Gorrrg** [PetterKraabol/Twitch-Chat-Downloader#5]
`Downloading raw JSON
Traceback (most recent call last):
  File "D:\Downloads\Software\(new)\Twitch-Chat-Downloader-master 2017-03-14\app.py", line 225, in <module>
    if ['srt', 'ass', 'ssa'].index(settings['format']) != -1:
ValueError: 'raw' is not in list

Downloading timestamped text
Traceback (most recent call last):
  File "D:\Downloads\Software\(new)\Twitch-Chat-Downloader-master 2017-03-14\app.py", line 225, in <module>
    if ['srt', 'ass', 'ssa'].index(settings['format']) != -1:
ValueError: 'timestamp' is not in list

Downloading relative timecoded text
Traceback (most recent call last):
  File "D:\Downloads\Software\(new)\Twitch-Chat-Downloader-master 2017-03-14\app.py", line 225, in <module>
    if ['srt', 'ass', 'ssa'].index(settings['format']) != -1:
ValueError: 'relative' is not in list`

**If array** expects one of the three subtitle strings. Which I fixed on my end by removing that **if array condition** and adding the **subtitleStart**, and **'.000000'** bugfix parts to the two respective **if settings['format'] == 'srt'** and **'ssa'|'ass'**.

**Comment by PetterKraabol** [comment]
Fixed in 9c63e764545e62ebcb5c8a5e3eee78179b0dec38. I'm getting too used to Javascript.

**Comment by Gorrrg** [comment]
Omg, lol. That was JS? :rofl:
