### ISSUE TITLE
Can't get json data from vod

### ISSUE THREAD

**Issue by OgulcanCelik** [PetterKraabol/Twitch-Chat-Downloader#54]
I'm trying to get chat data of a vod with the id of "304617140". 

python app.py -v 304617140 --format all --output ~/Downloads/Twitch

With this parameters, I get this error:
`Traceback (most recent call last):
  File "app.py", line 45, in <module>
    main()
  File "app.py", line 24, in main
    app.arguments.input = app.download(app.arguments.video, 'json')
  File "C:\Users\Garavel\Dev\Twitch-Chat-Downloader\app\downloader.py", line 26, in download
    lines, output = formats.use(format_name, video)
  File "C:\Users\Garavel\Dev\Twitch-Chat-Downloader\formats\formats.py", line 16, in use
    return _json.use(video)
  File "C:\Users\Garavel\Dev\Twitch-Chat-Downloader\formats\json.py", line 16, in use
    for comment in video.comments:
  File "C:\Users\Garavel\Dev\Twitch-Chat-Downloader\twitch\api.py", line 40, in comments
    fragment = comment_fragment(video_id, fragment['_next'])
  File "C:\Users\Garavel\Dev\Twitch-Chat-Downloader\twitch\api.py", line 30, in comment_fragment
    return get('videos/{}/comments'.format(video_id), {'cursor': cursor}).json()
  File "C:\Users\Garavel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Garavel\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Garavel\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Garavel\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 25684 (char 25683)`

Any idea why?

**Comment by OgulcanCelik** [comment]
I don't know why it happened but it seems it's fixed now.
