### ISSUE TITLE
Import errors

### ISSUE THREAD

**Issue by lcheung90** [PetterKraabol/Twitch-Chat-Downloader#60]
I installed the requirements using: 
`pip install -U --user -r requirements.txt`

I am using python 3.6

```bash
python3 app.py -v 1234567
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    import app
  File "/home/lcheungchang/Twitch-Chat-Downloader/app/__init__.py", line 3, in <module>
    from .downloader import download, draw_progress
  File "/home/lcheungchang/Twitch-Chat-Downloader/app/downloader.py", line 6, in <module>
    import app.formats as formats
  File "/home/lcheungchang/Twitch-Chat-Downloader/app/formats/__init__.py", line 1, in <module>
    from .formats import use
  File "/home/lcheungchang/Twitch-Chat-Downloader/app/formats/formats.py", line 4, in <module>
    import app.twitch as twitch
  File "/home/lcheungchang/Twitch-Chat-Downloader/app/twitch/__init__.py", line 1, in <module>
    from .video import Video
  File "/home/lcheungchang/Twitch-Chat-Downloader/app/twitch/video.py", line 5, in <module>
    import twitch
  File "/home/lcheungchang/.local/lib/python3.6/site-packages/twitch/__init__.py", line 1, in <module>
    from .chat import Chat
  File "/home/lcheungchang/.local/lib/python3.6/site-packages/twitch/chat/__init__.py", line 1, in <module>
    from .chat import Chat
  File "/home/lcheungchang/.local/lib/python3.6/site-packages/twitch/chat/chat.py", line 1, in <module>
    from rx.subjects import Subject
ModuleNotFoundError: No module named 'rx'
```

**Comment by PetterKraabol** [comment]
Hi, TCD requires Python 3.7 or newer.

Use this command to make sure you're using the right pip:
`python3 -m pip install --user -r requirements.txt`
