### ISSUE TITLE
 Unauthorized for url

### ISSUE THREAD

**Issue by FlamesoFF** [PetterKraabol/Twitch-Chat-Downloader#64]
```
Traceback (most recent call last):
  File "c:\users\flamesoff\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\flamesoff\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\flamesoff\AppData\Local\Programs\Python\Python37-32\Scripts\tcd.exe\__main__.py", line 9, in <module>
  File "c:\users\flamesoff\appdata\local\programs\python\python37-32\lib\site-packages\tcd\__init__.py", line 75, in main
    Downloader().videos(Arguments().video_ids)
  File "c:\users\flamesoff\appdata\local\programs\python\python37-32\lib\site-packages\tcd\downloader.py", line 160, in videos
    for video in self.helix_api.videos(video_ids):
  File "c:\users\flamesoff\appdata\local\programs\python\python37-32\lib\site-packages\twitch\helix\helix.py", line 41, in videos
    return helix.Videos(self.api(), video_ids=video_ids, **kwargs)
  File "c:\users\flamesoff\appdata\local\programs\python\python37-32\lib\site-packages\twitch\helix\videos.py", line 46, in __init__
    self._download_video_ids(**self._kwargs)
  File "c:\users\flamesoff\appdata\local\programs\python\python37-32\lib\site-packages\twitch\helix\videos.py", line 126, in _download_video_ids
    videos: List['helix.Video'] = self._videos_fragment(ignore_cache=True, **kwargs)
  File "c:\users\flamesoff\appdata\local\programs\python\python37-32\lib\site-packages\twitch\helix\videos.py", line 87, in _videos_fragment
    response: dict = self._api.get(self._path, params=kwargs, ignore_cache=ignore_cache)
  File "c:\users\flamesoff\appdata\local\programs\python\python37-32\lib\site-packages\twitch\api.py", line 56, in get
    return self.request('GET', path, ignore_cache, params=params, headers=self._headers(headers), **kwargs)
  File "c:\users\flamesoff\appdata\local\programs\python\python37-32\lib\site-packages\twitch\api.py", line 50, in request
    response.raise_for_status()
  File "c:\users\flamesoff\appdata\local\programs\python\python37-32\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.twitch.tv/helix/videos?id=408934125

```

**Comment by PetterKraabol** [comment]
Hi, your client ID is most likely invalid.
Run tcd again with `--client-id` and paste your client id.
