### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by jamestonkin** [PetterKraabol/Twitch-Chat-Downloader#71]
When trying to download the chat from a 2.5 hour VOD in JSON, it got to about 40%, then same VOD just IRC it got to 5% then get the following errors below. I included my packages in case I'm missing something. 

(twchat) C:\Users\jtonkin\Documents\twchat\Twitch-Chat-Downloader>tcd --video 398390963 --format irc  --output ~/Downloads
Highlight: COMPLETING DARK SOULS WITHOUT DYING--IF I DIE I DONATE 2K TO CHARITY
Traceback (most recent call last):
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\urllib3\connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\urllib3\connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\urllib3\connection.py", line 370, in connect
    ssl_context=context)
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\urllib3\util\ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\urllib3\connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\urllib3\util\retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\urllib3\connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\urllib3\connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\urllib3\connection.py", line 370, in connect
    ssl_context=context)
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\urllib3\util\ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jtonkin\AppData\Local\Continuum\anaconda3\envs\twchat\Scripts\tcd.exe\__main__.py", line 9, in <module>
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\tcd\__init__.py", line 79, in main
    Downloader().videos(Arguments().video_ids)
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\tcd\downloader.py", line 183, in videos
    self.video(video)
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\tcd\downloader.py", line 143, in video
    for formatted_comment, comment in comment_tuple:
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\tcd\formats\custom.py", line 29, in comment_generator
    for comment in comments:
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\twitch\v5\resources\comments.py", line 22, in __iter__
    fragment = self.fragment(fragment['_next'])
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\twitch\v5\resources\comments.py", line 16, in fragment
    return self._api.get(self._path.format(video_id=self._video_id), params={'cursor': cursor})
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\twitch\api.py", line 109, in get
    return self.request('GET', path, ignore_cache, params=params, headers=self._headers(headers), **kwargs)
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\twitch\api.py", line 88, in request
    response = requests.Session().send(request)
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\jtonkin\appdata\local\continuum\anaconda3\envs\twchat\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))

(twchat) C:\Users\jtonkin\Documents\twchat\Twitch-Chat-Downloader>conda list
# packages in environment at C:\Users\jtonkin\AppData\Local\Continuum\anaconda3\envs\twchat:
#
# Name                    Version                   Build  Channel
ca-certificates           2019.5.15                     1
certifi                   2019.6.16                py37_1
chardet                   3.0.4                     <pip>
idna                      2.8                       <pip>
openssl                   1.1.1c               he774522_1
pip                       19.2.2                   py37_0
python                    3.7.4                h5263a28_0
python-dateutil           2.8.0                     <pip>
pytz                      2019.2                    <pip>
requests                  2.22.0                    <pip>
Rx                        3.0.1                     <pip>
setuptools                41.0.1                   py37_0
six                       1.12.0                    <pip>
sqlite                    3.29.0               he774522_0
tcd                       3.1.3                     <pip>
twitch-python             0.0.15                    <pip>
urllib3                   1.25.3                    <pip>
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
wheel                     0.33.4                   py37_0
wincertstore              0.2                      py37_0

(twchat) C:\Users\jtonkin\Documents\twchat\Twitch-Chat-Downloader>

**Comment by PetterKraabol** [comment]
I'm not able to replicate this. Did you check https://twitchstatus.com to see if their API server was stable?

If you make too many API requests, you will be temporarily blocked, but downloading all messages worked fine on my end.
