### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by sori424** [PetterKraabol/Twitch-Chat-Downloader#73]
`skkuui-MacBook-Pro:Versions skku$ tcd --video cloazky --format irc
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/tcd", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tcd/__init__.py", line 41, in main
    Arguments(parser.parse_args().__dict__)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tcd/singleton.py", line 9, in __call__
    cls._instances[cls] = super().__call__(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tcd/arguments.py", line 69, in __init__
    self.video_ids = [int(video_id) for video_id in arguments[Arguments.Name.VIDEO].lower().split(',')]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tcd/arguments.py", line 69, in <listcomp>
    self.video_ids = [int(video_id) for video_id in arguments[Arguments.Name.VIDEO].lower().split(',')]
ValueError: invalid literal for int() with base 10: 'cloazky'
skkuui-MacBook-Pro:Versions skku$ tcd --channel sodapoppin --first=5
sodapoppin
driklgjfndfghdfgthrs
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/tcd", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tcd/__init__.py", line 82, in main
    Downloader().channels(Arguments().channels)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tcd/downloader.py", line 195, in channels
    self.video(video)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tcd/downloader.py", line 140, in video
    with open(output, '+w', encoding='utf-8') as file:
PermissionError: [Errno 13] Permission denied: './481948530.txt'`

Plz provide solution for this problem.

**Comment by PetterKraabol** [comment]
Check your write permissions in the home directory.
You might want to try installing tcd with the user flag: `pip3 install --user tcd` instead
