### ISSUE TITLE
NotADirectoryError: [Errno 20] Not a directory: tcd-3.1.3-py3.8.egg/tcd/settings.reference.json

### ISSUE THREAD

**Issue by davispuh** [PetterKraabol/Twitch-Chat-Downloader#76]
Just built from git master and getting this error.

```
$ tcd
/usr/lib/python3.8/site-packages/tcd-3.1.3-py3.8.egg/tcd/formats/ssa.py:89: SyntaxWarning: "is" with a literal. Did you mean "=="?
/usr/lib/python3.8/site-packages/tcd-3.1.3-py3.8.egg/tcd/formats/ssa.py:89: SyntaxWarning: "is" with a literal. Did you mean "=="?
/usr/lib/python3.8/site-packages/tcd-3.1.3-py3.8.egg/tcd/formats/ssa.py:89: SyntaxWarning: "is" with a literal. Did you mean "=="?
/usr/lib/python3.8/site-packages/tcd-3.1.3-py3.8.egg/tcd/formats/ssa.py:89: SyntaxWarning: "is" with a literal. Did you mean "=="?
Traceback (most recent call last):
  File "/usr/bin/tcd", line 11, in <module>
    load_entry_point('tcd==3.1.3', 'console_scripts', 'tcd')()
  File "/usr/lib/python3.8/site-packages/tcd-3.1.3-py3.8.egg/tcd/__init__.py", line 42, in main
  File "/usr/lib/python3.8/site-packages/tcd-3.1.3-py3.8.egg/tcd/singleton.py", line 9, in __call__
  File "/usr/lib/python3.8/site-packages/tcd-3.1.3-py3.8.egg/tcd/settings.py", line 29, in __init__
  File "/usr/lib/python3.8/site-packages/tcd-3.1.3-py3.8.egg/tcd/settings.py", line 84, in out_of_date
  File "/usr/lib/python3.8/site-packages/tcd-3.1.3-py3.8.egg/tcd/settings.py", line 59, in load
NotADirectoryError: [Errno 20] Not a directory: '/usr/lib/python3.8/site-packages/tcd-3.1.3-py3.8.egg/tcd/settings.reference.json
```

It seems it's because when you install it, it gets packaged as single file `tcd-3.1.3-py3.8.egg` which is egg archive.

I'm using Python 3.8.0 on ArchLinux

**Comment by PetterKraabol** [comment]
Hi, I'll look into this. This happens when using `./setup.py install`

For now, you can install with pip with `pip install -e .` (-e flag if you want to install in editable mode).
