### ISSUE TITLE
succeed to download a chat before but it didn't work after a month

### ISSUE THREAD

**Issue by LydiaHappy** [PetterKraabol/Twitch-Chat-Downloader#77]
Here is the information in Linux shell.
```
root@ivpser:/home/lydia/PrideClip# tcd --video 789654123
 Traceback (most recent call last):
  File "/usr/local/bin/tcd", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/tcd/__init__.py", line 79, in main
    Downloader().videos(Arguments().video_ids)
  File "/usr/local/lib/python3.7/site-packages/tcd/downloader.py", line 181, in videos
    for video in self.helix_api.videos(video_ids):
  File "/usr/local/lib/python3.7/site-packages/twitch/helix/helix.py", line 51, in videos
    return helix.Videos(self.api, video_ids=video_ids, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/twitch/helix/resources/videos.py", line 46, in __init__
    self._download_video_ids()
  File "/usr/local/lib/python3.7/site-packages/twitch/helix/resources/videos.py", line 125, in _download_video_ids
    videos: List[helix.Video] = self._next_videos_page(ignore_cache=True)
  File "/usr/local/lib/python3.7/site-packages/twitch/helix/resources/videos.py", line 84, in _next_videos_page
    response: dict = self._next_page(ignore_cache=ignore_cache)
  File "/usr/local/lib/python3.7/site-packages/twitch/helix/resources/resource.py", line 98, in _next_page
    response: dict = self._api.get(self._path, params=self._kwargs, ignore_cache=ignore_cache)
  File "/usr/local/lib/python3.7/site-packages/twitch/api.py", line 111, in get
    return self.request('GET', path, ignore_cache, params=params, headers=self._headers(headers), **kwargs)
  File "/usr/local/lib/python3.7/site-packages/twitch/api.py", line 100, in request
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.twitch.tv/helix/videos?id=789654123
```
sry for bothering but I'm really wondering what to do. I searched on Internet and twitch API seems to be changed a lot.

**Comment by PetterKraabol** [comment]
Hi, it looks like the video is no longer available (https://www.twitch.tv/videos/789654123).

Past broadcasts are only available for 14 days for regular channels and 60 days for partnered. 
https://help.twitch.tv/s/article/videos-on-demand?language=en_US#managing

**Comment by LydiaHappy** [comment]
> Hi, it looks like the video is no longer available (https://www.twitch.tv/videos/789654123).
> 
> Past broadcasts are only available for 14 days for regular channels and 60 days for partnered.
> https://help.twitch.tv/s/article/videos-on-demand?language=en_US#managing

thx a lot (´•༝•`)Can’t believe I just forget to check the video...sry for bothering and thank u so much.
