### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by MrAmericanMike** [PetterKraabol/Twitch-Chat-Downloader#82]
Whenever I try

`tcd --video 559699847 --format irc --output ~/Downloads`

I get this on console

```
Traceback (most recent call last):
  File "c:\users\supervisor\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\supervisor\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Supervisor\AppData\Local\Programs\Python\Python37-32\Scripts\tcd.exe\__main__.py", line 9, in <module>
  File "c:\users\supervisor\appdata\local\programs\python\python37-32\lib\site-packages\tcd\__init__.py", line 79, in main
    Downloader().videos(Arguments().video_ids)
  File "c:\users\supervisor\appdata\local\programs\python\python37-32\lib\site-packages\tcd\downloader.py", line 181, in videos
    for video in self.helix_api.videos(video_ids):
  File "c:\users\supervisor\appdata\local\programs\python\python37-32\lib\site-packages\twitch\helix\helix.py", line 51, in videos
    return helix.Videos(self.api, video_ids=video_ids, **kwargs)
  File "c:\users\supervisor\appdata\local\programs\python\python37-32\lib\site-packages\twitch\helix\resources\videos.py", line 46, in __init__
    self._download_video_ids()
  File "c:\users\supervisor\appdata\local\programs\python\python37-32\lib\site-packages\twitch\helix\resources\videos.py", line 125, in _download_video_ids
    videos: List[helix.Video] = self._next_videos_page(ignore_cache=True)
  File "c:\users\supervisor\appdata\local\programs\python\python37-32\lib\site-packages\twitch\helix\resources\videos.py", line 84, in _next_videos_page
    response: dict = self._next_page(ignore_cache=ignore_cache)
  File "c:\users\supervisor\appdata\local\programs\python\python37-32\lib\site-packages\twitch\helix\resources\resource.py", line 98, in _next_page
    response: dict = self._api.get(self._path, params=self._kwargs, ignore_cache=ignore_cache)
  File "c:\users\supervisor\appdata\local\programs\python\python37-32\lib\site-packages\twitch\api.py", line 111, in get
    return self.request('GET', path, ignore_cache, params=params, headers=self._headers(headers), **kwargs)
  File "c:\users\supervisor\appdata\local\programs\python\python37-32\lib\site-packages\twitch\api.py", line 100, in request
    response.raise_for_status()
  File "c:\users\supervisor\appdata\local\programs\python\python37-32\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.twitch.tv/helix/videos?id=559699847
```

I'm guessing it's some authorization issues, but I thought chats were public. Maybe I'm missing some details here.

**Comment by BradleyPelton** [comment]
That command worked for me 
`tcd --video 559699847 --format irc --output ~/Downloads` 

Maybe there is an issue with your twitch client ID. Try sending an API request with that client ID to helix API and see if it accepts your client ID.

**Comment by MrAmericanMike** [comment]
> 
> 
> That command worked for me
> `tcd --video 559699847 --format irc --output ~/Downloads`
> 
> Maybe there is an issue with your twitch client ID. Try sending an API request with that client ID to helix API and see if it accepts your client ID.

Yes that's probably what I didn't do. Is this something that TCD can do? Is there any guide? Thanks a lot.

**Comment by PetterKraabol** [comment]
You can provide your client id with the --client-id argument
