### ISSUE TITLE
Is this an OAuth issue?

### ISSUE THREAD

**Issue by siukk** [PetterKraabol/Twitch-Chat-Downloader#89]
Traceback (most recent call last):
  File "app.py", line 46, in <module>
    main()
  File "app.py", line 25, in main
    app.arguments.input = app.download(app.arguments.video, 'json')
  File "C:\Users\Downloads\Twitch-Chat-Downloader\app\downloader.py", line 24, in download
    video: twitch.Video = twitch.Video(video_id)
  File "C:\Users\Downloads\Twitch-Chat-Downloader\app\twitch\video.py", line 41, in __init__
    video: helix.Video = helix.video(video_id)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\twitch\helix\helix.py", line 36, in video
    return helix.Videos(self.api(), video_ids=None, **kwargs)[0]
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\twitch\helix\videos.py", line 45, in __init__
    self._api.get(self._path, params=kwargs)['data']]
KeyError: 'data'

**Comment by PetterKraabol** [comment]
See https://github.com/PetterKraabol/Twitch-Chat-Downloader/issues/88#issuecomment-636178923
