### ISSUE TITLE
Error on Windows when logging enabled and video name contains non-cp1252 characters

### ISSUE THREAD

**Issue by ashtov** [PetterKraabol/Twitch-Chat-Downloader#90]
```
J:\twitch-logs\attempt2>tcd --format default,json --verbose --debug --log --vide
o 229761450
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 193, in _run_module_as_mai
n
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\tcd.exe\__main__.py", line 7, in <modu
le>
  File "C:\Users\MeFigaYoma\AppData\Roaming\Python\Python38\site-packages\tcd\__
init__.py", line 89, in main
    Downloader().videos(Arguments().video_ids)
  File "C:\Users\MeFigaYoma\AppData\Roaming\Python\Python38\site-packages\tcd\do
wnloader.py", line 182, in videos
    Logger().log(format('\n{}'.format(video.title)), Log.REGULAR)
  File "C:\Users\MeFigaYoma\AppData\Roaming\Python\Python38\site-packages\tcd\lo
gger.py", line 59, in log
    self.save()
  File "C:\Users\MeFigaYoma\AppData\Roaming\Python\Python38\site-packages\tcd\lo
gger.py", line 107, in save
    [file.write('{}\n'.format(log.full())) for log in self.logs]
  File "C:\Users\MeFigaYoma\AppData\Roaming\Python\Python38\site-packages\tcd\lo
gger.py", line 107, in <listcomp>
    [file.write('{}\n'.format(log.full())) for log in self.logs]
  File "c:\program files\python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u222a' in position
55: character maps to <undefined>
```
No issue without --log.

**Comment by PetterKraabol** [comment]
Thanks, #90 has been released with v3.2.1
