### ISSUE TITLE
cursor error

### ISSUE THREAD

**Issue by AdrianTimotheus** [PetterKraabol/Twitch-Chat-Downloader#96]
Traceback (most recent call last):                                                                                        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main                                                                                              return _run_code(code, main_globals, None,                                                                            File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code                                                                                                         exec(code, run_globals)                                                                                               File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts\tcd.exe\__main__.py", line 9, in <module>                                                             File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tcd\__init__.py", line 92, in main                                                                Downloader().channels(Arguments().channels)                                                                           File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tcd\downloader.py", line 195, in channels                                                         self.video(video)                                                                                                     File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tcd\downloader.py", line 143, in video                                                            for formatted_comment, comment in comment_tuple:                                                                      File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tcd\formats\custom.py", line 29, in comment_generator                                             for comment in comments:                                                                                              File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\twitch\v5\resources\comments.py", line 22, in __iter__                                            fragment = self.fragment(fragment['_next'])                                                                           File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\twitch\v5\resources\comments.py", line 16, in fragment                                            return self._api.get(self._path.format(video_id=self._video_id), params={'cursor': cursor})                           File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\twitch\api.py", line 111, in get                                                                  return self.request('GET', path, ignore_cache, params=params, headers=self._headers(headers), **kwargs)               File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\twitch\api.py", line 100, in request                                                              response.raise_for_status()                                                                                           File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\requests\models.py", line 941, in raise_for_status                                                raise HTTPError(http_error_msg, response=self)                                                                      requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.twitch.tv/v5/videos/650174057/comments?cursor=eyJpZCI6IjNiOGU5ZTRjLWViNjQtNGZkYy05M2MxLTgyMDM1M2Y3MjMwMyIsImhrIjoiYnJvYWRjYXN0OjM4NjYwOTkzMTg0Iiwic2siOiJBQUFBZ2F6T2tZQVdHRUpja3pyUWdBIn0f

This happens everytime I execute the command, apparently the cursor hash is always the same. I accidentally double tap on the command line when the script is running and suddenly the script breaks. How to fix this issue? Thank you very much

**Comment by eugenechung81** [comment]
I'm getting the same Internal Error response. 

requests.exceptions.HTTPError: 503 Server Error: Backend.max_conn reached for url: https://api.twitch.tv/v5/videos/647174162/comments?cursor=

requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.twitch.tv/v5/videos/647174162/comments?cursor=

Going straight to the VOD itself, the chat doesn't seem to load so it looks like this is on Twitch's side.  We might just need to wait it out until they stabilizes their APIs.

**Comment by garoto** [comment]
Twitch services are crapping up for the past hour or so. Just wait.

**Comment by AdrianTimotheus** [comment]
I dont know what happened but after I opened my laptop again at this time it suddenly worked and the cursor is no longer error.
