### ISSUE TITLE
getaddrinfo failed

### ISSUE THREAD

**Issue by CyrusD123** [PetterKraabol/Twitch-Chat-Downloader#99]
```Traceback (most recent call last):
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\site-packages\urllib3\util\connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 308, in connect
    conn = self._new_conn()
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000198DC25EC10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.twitch.tv', port=443): Max retries exceeded with url: /v5/videos/474363749/comments?cursor=eyJpZCI6IjkxZGRkMWNhLTUxYzgtNGI3My05YzhlLTAyMTIyNTlhNzNkYiIsImhrIjoiYnJvYWRjYXN0OjM1NDgxNzU1MjgwIiwic2siOiJBQUFVMUhlSG9zQVZ2OEdyNnN1UndBIn0f (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000198DC25EC10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Cyrus Desai\AppData\Local\Programs\Python\Python38\Scripts\tcd.exe\__main__.py", line 7, in <module>
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\site-packages\tcd\__init__.py", line 89, in main
    Downloader().videos(Arguments().video_ids)
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\site-packages\tcd\downloader.py", line 183, in videos
    self.video(video)
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\site-packages\tcd\downloader.py", line 143, in video
    for formatted_comment, comment in comment_tuple:
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\site-packages\tcd\formats\custom.py", line 29, in comment_generator
    for comment in comments:
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\site-packages\twitch\v5\resources\comments.py", line 22, in __iter__
    fragment = self.fragment(fragment['_next'])
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\site-packages\twitch\v5\resources\comments.py", line 16, in fragment
    return self._api.get(self._path.format(video_id=self._video_id), params={'cursor': cursor})
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\site-packages\twitch\api.py", line 111, in get
    return self.request('GET', path, ignore_cache, params=params, headers=self._headers(headers), **kwargs)
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\site-packages\twitch\api.py", line 90, in request
    response = requests.Session().send(request)
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\CyrusD123\appdata\local\programs\python\python38\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.twitch.tv', port=443): Max retries exceeded with url: /v5/videos/474363749/comments?cursor=eyJpZCI6IjkxZGRkMWNhLTUxYzgtNGI3My05YzhlLTAyMTIyNTlhNzNkYiIsImhrIjoiYnJvYWRjYXN0OjM1NDgxNzU1MjgwIiwic2siOiJBQUFVMUhlSG9zQVZ2OEdyNnN1UndBIn0f (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000198DC25EC10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))```

**Comment by garoto** [comment]
`[Errno 11001] getaddrinfo failed`

DNS name resolution issue on your end most likely.
